server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: store-front

management:
  endpoints:
    web:
      exposure:
        include: health
  thymeleaf:
    cache: false

app:
  product-api-url: ${PRODUCT_API_URL:http://localhost:8081}
  order-api-url: ${ORDER_API_URL:http://localhost:8082}
